#!/usr/bin/env ruby

$:.unshift File.join(File.dirname(__FILE__), '../lib')
require 'dynosaur/watcher'
require 'eventmachine'

$stdout.sync = true
$stderr.sync = true

EventMachine.run do
  dyno_types = ENV['DYNO_TYPES'].split(/[,\s]+/)
  watcher = Dynosaur::Watcher.new(ENV['HEROKU_APP'], ENV['HEROKU_TOKEN'], dyno_types)
  watcher.boot
end
